fixes

diff --git a/templates/fast_luks.j2 b/templates/fast_luks.j2
--- a/templates/fast_luks.j2
+++ b/templates/fast_luks.j2
@@ -88,7 +88,7 @@ function lock(){
     if mkdir "${LOCKDIR}" &>/dev/null; then
       # lock succeeded, I'm storing the PID 
       echo "$$" >"${PIDFILE}"
-      echo -e "LUKS script for ELIXIR-IIB use case in INDIGO. Starting log file: $now"
+      echo -e "[$STAT] LUKS script for ELIXIR-IIB use case in INDIGO. Starting log file: $now"
 
     else
 
@@ -99,22 +99,22 @@ function lock(){
       #  Thanks to Grzegorz Wierzowiecki for pointing out this race condition on
       #  http://wiki.grzegorz.wierzowiecki.pl/code:mutex-in-bash
       if [ $? != 0 ]; then
-        echo "Another script instance is active: PID ${OTHERPID} " >&2
+        echo "[Error] Another script instance is active: PID ${OTHERPID} " >&2
         exit ${ENO_LOCKFAIL}
       fi
 
       if ! kill -0 $OTHERPID &>/dev/null; then
         # lock is stale, remove it and restart
-        echo "removing fake lock file of nonexistant PID ${OTHERPID}" >&2
+        echo "[$STAT] Removing fake lock file of nonexistant PID ${OTHERPID}" >&2
         rm -rf "${LOCKDIR}"
-        echo "[statsgen] restarting script..." >&2
+        echo "[$STAT] Restarting LUKS script" >&2
         exec "$0" "$@"
       else
         # lock is valid and OTHERPID is active - exit, we're locked!
-        echo "Lock failed, PID ${OTHERPID} is active" >&2
-        echo "Another $STAT process is active" >&2
-        echo "If you're sure $STAT is not already running,"
-        echo "you can remove $LOCKDIR and restart $STAT" >&2
+        echo "[Error] Lock failed, PID ${OTHERPID} is active" >&2
+        echo "[Error] Another $STAT process is active" >&2
+        echo "[Error] If you're sure $STAT is not already running,"
+        echo "[Error] You can remove $LOCKDIR and restart $STAT" >&2
         exit ${ENO_LOCKFAIL}
       fi
     fi
@@ -130,7 +130,7 @@ function unlock(){
 
   # the following handler will exit the script upon receiving these signals
   # the trap on "0" (EXIT) from above will be triggered by this trap's "exit" command!
-  trap 'echo "[$STAT] Killed by a signal."  >> "$LOGFILE" 2>&1 
+  trap 'echo "[$STAT] Killed by signal."  >> "$LOGFILE" 2>&1 
         exit ${ENO_RECVSIG}' 1 2 3 15
 }
 
@@ -175,8 +175,8 @@ function install_cryptsetup(){
 function check_cryptsetup(){
   echo -e "\n==================================="
   echo -e "Check if the required applications are installed..."
-  type -P dmsetup &>/dev/null || echo -e "$red dmestup is not installed. Installing... $none" #TODO add install device_mapper
-  type -P cryptsetup &>/dev/null || { echo -e "$red cryptsetup is not installed. Installing... $none"; install_cryptsetup  >> "$LOGFILE" 2>&1; echo -e "$green cryptsetup installed! $none"; }
+  type -P dmsetup &>/dev/null || echo -e "dmestup is not installed. Installing..." #TODO add install device_mapper
+  type -P cryptsetup &>/dev/null || { echo -e "cryptsetup is not installed. Installing.."; install_cryptsetup  >> "$LOGFILE" 2>&1; echo -e "$green cryptsetup installed! $none"; }
 }
 
 #____________________________________
@@ -242,11 +242,11 @@ function open_device(){
   if [ ! -b /dev/mapper/${cryptdev} ]; then
     cryptsetup luksOpen $device $cryptdev
   else
-    echo -e "$red Crypt device already exists! Please check logs: $LOGFILE $none"
+    echo -e "[Error] Crypt device already exists! Please check logs: $LOGFILE"
     # log
-    echo -e "\nError: Unable to luksOpen device. " >> "$LOGFILE" 2>&1
-    echo -e "Error: /dev/mapper/${cryptdev} already exists." >> "$LOGFILE" 2>&1
-    echo -e " Mounting $device to $mountpoint again." >> "$LOGFILE" 2>&1
+    echo -e "[Error] Unable to luksOpen device. " >> "$LOGFILE" 2>&1
+    echo -e "[Error] /dev/mapper/${cryptdev} already exists." >> "$LOGFILE" 2>&1
+    echo -e "[Error]  Mounting $device to $mountpoint again." >> "$LOGFILE" 2>&1
     mount $device $mountpoint >> "$LOGFILE" 2>&1
     # end log
     unlock # unlocking script instance
@@ -287,10 +287,9 @@ function create_fs(){
   echo -e "Creating filesystem..."
   mkfs.${filesystem} /dev/mapper/${cryptdev} #Do not redirect mkfs, otherwise no interactive mode!
   if [ $? != 0 ]; then
-    echo -e "$red Error: while creating ${filesystem} filesystem. Please check logs: $LOGFILE $none"
-    # log
-    echo -e "Error: Command mkfs failed!" >> "$LOGFILE" 2>&1 #TODO redirect log
-    # end log
+    echo -e "[Error] While creating ${filesystem} filesystem. Please check logs: $LOGFILE"
+    # update log
+    echo -e "[Error] Command mkfs failed!" >> "$LOGFILE" 2>&1
     unlock
     exit 1
   fi
@@ -339,8 +338,8 @@ function save_info(){
 #____________________________________
 function end_encrypt_procedure(){
   # send signal to unclok waiting condition for automation software (e.g Ansible)
-  echo -e "LUKS encryption completed." > $SUCCESS_FILE
-  echo -e "\n$green Successful. You will be automatically kicked out by this server. Galaxy will be automatically installed! $none"
+  echo -e "[$STAT] LUKS encryption completed." > $SUCCESS_FILE
+  echo -e "[$STAT] SUCCESSFUL. You will be automatically kicked out by this server. Galaxy will be automatically installed!"
 }
 
 #____________________________________
